/* File Name: inGameActionType.js                                   *
 * Description: Action Types for in Game Data                       */

const InGameActionTypes = {
    LOADING_INPROGRESS: 'LOADING_INPROGRESS',
    LOADING_COMPLETE: 'LOADING_COMPLETE',
    SET_GAME_DIFFICULTY: 'SET_GAME_DIFFICULTY',
    UPDATE_FAV_ARTIST_SONGS_URIS: 'UPDATE_FAV_ARTIST_SONGS_URIS',
    GET_QUESTIONS: 'GET_QUESTIONS',
    TURN_GAME_ON: 'TURN_GAME_ON',
    GENERATE_RESULTS: 'GENERATE_RESULTS',
    RESTART_GAME: 'RESTART_GAME',
    NEXT_QUESTION: 'NEXT_QUESTION',
    CORRECT_ANSWER: 'CORRECT_ANSWER',
    USER_CHEATED: 'USER_CHEATED',
    ADD_TO_USER_RESPONSE_LOG: 'ADD_TO_USER_RESPONSE_LOG',
    INGAME_ERROR: 'INGAME_ERROR'
}

export default InGameActionTypes